### ISSUE TITLE
third party review on build process and GitHub actions

### ISSUE THREAD

**Issue by turbomam** [kaiiam/mifc#17]
I'll get someone to double check us esp. regarding `make all-all` from `project.Makefile` 

for example, trying to avoid deletion of `https://github.com/kaiiam/mifc/blob/main/src/mifc/datamodel/__init__.py`

the presence of  `tsv-data-to-yam` and `src/data/examples/valid/%.yaml` are intentional on my part, so that the TSV example data files get checked during `linkml-run-examples`

**Comment by turbomam** [comment]
see also
- https://github.com/kaiiam/mifc/issues/18

**Comment by turbomam** [comment]
see PR notes:
- https://github.com/kaiiam/mifc/pull/16

**Comment by turbomam** [comment]
I don't understand the presence of `.github/workflows/deploy-docs.yaml.rej` or why there are conflict indicators in `.github/workflows/deploy-docs.yaml.rej`

**Comment by kaiiam** [comment]
@sujaypatil96 if you have time would it be possible for you to help check on this. Mark and I have perhaps made some deviations from standard LinkML practices. I'm trying my best not to, just trying to use the cookie cutter as is but we've had to make a few changes not sure if those are relevant here, or if this is caused by something else. Perhaps this project could help to sort some kinks in the cookie cutter repo generation process. Thanks in advance if you might have time.

Much obliged,
Kai

**Comment by turbomam** [comment]
I think @sujaypatil96's assistance would be especially useful for the documentation build process.

**Comment by turbomam** [comment]
@kai,  `.github/workflows/deploy-docs.yaml.rej` was generated when you did `cruft update` as part of https://github.com/kaiiam/mifc/commit/fc059b3e767ed99f25f439ecb2be69551e7e9719

**Comment by kaiiam** [comment]
@turbomam when I regenerated it was that a problem or did it potentially fix something?
