### ISSUE TITLE
Create enumeration with ISO country codes

### ISSUE THREAD

**Issue by kaiiam** [kaiiam/mifc#21]
As discussed in #19 we'll have at least two fields which are about a countries either of origin or acquisition currently `food_acquisition_country`, `food_origin_country`. We should create an enum for these using the ISO codes. As discussed in #19 the question is if we should use the two ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)) or three letter ISO codes [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3). 

I am pretty convinced by the arguments in https://andrewwhitby.com/2021/01/08/the-right-country-codes/ that the 3 letter code is better and less ambiguous than the 2 letter code, but happy to hear arguments to the contrary. [The Periodic Table of Food Initiative (PTFI)](https://foodperiodictable.org/) for example is using the 2 letter codes currently. 

My currently plan is use python to parse the wiki page for ISO codes or similar and generate the linkML enum which uses the ISO 3 letter codes as the enum values with their the country names as the country names as the `Description`. Perhaps we can also map that to the ISO 2 letter codes in the Enum TBD (for me) how to do that correctly in LinkML. I don't think Meaning is correct as ISO country codes aren't IRIs/curies from a semantic web resource as far as I'm aware. 

Suggestions welcome.

**Comment by GregLyonJIFSAN** [comment]
Hello, @kaiiam, would the map from two-letter to three-letter country codes allow conversion to be done automatically using the linkml-convert tool? This would be an advantage over keeping (and periodically updating) a separate table of code conversions in the Foundation Foods QC application.

**Comment by kaiiam** [comment]
> would the map from two-letter to three-letter country codes allow conversion to be done automatically using the linkml-convert tool? 

At the moment I don't think so that'd be an interesting question for the LinkML team if that could be something which would be possible. Aka if there was an Enum the values of which had mappings to other strings would linkML validate or convert be able to do the mappings and auto-convert? @sujaypatil96 @turbomam? let me know what you guys think.

For example if we had an ENUM with the iso3 letter code as the value, and the iso2 code as the `Meaning`, could we use linkML convert or something else to auto convert data that had the 2 letter codes to the 3 letter codes as we'd be specifying in the enum? 

Value | Meaning | Description
-- | -- | --
AFG | AF | Afghanistan
AUS | AU | Australia

My understanding is that the meaning slot is suppose to be curies so perhaps it wouldn't work with strings. But please weigh in if this maybe possible.

**Comment by turbomam** [comment]
Yes, `meaning`s **must** be CURIes or URIs, never strings. _You can put bare strings into the meanings, but then the LinkML tools will get confused because they will think the CURIes are all relative to some base prefix_, and in my opinion LinkML doesn't t have good tooling for that. **Just use CURIes**.

That doesn't mean that you aren't on to something important!

I can't imagine any real content conversion taking place during `linkml-convert`, with one important exception. **When converting to RDF, the permissible value becomes a class and the CURIe for will be the** `meaning` value. That means, if you populate your `meaning`s with CURIes from some some other dataset about countries or other locations, and you load the RDF serialization of your data and the RDF serialization of that location dataset into the same RDF triple-store database, you could build an excellent knowledge graph of information about food components with respect to geographical or geopolitical locations. You can extend this pattern in may additional ways, but I'll get off the RDF soapbox now.

You can also annotate your permissible values with all sorts of other string or CURIe values in all sorts of other metaslots, but a conversion of values will likely have to be implemented in some external logic, using a [SchemaView](https://linkml.io/linkml/developers/schemaview.html) or the Python representation of your schema as a guide. I could start you with a minimal example, but somebody from you team would have to do the bulk of the work.

It's also possible that you could implement some conversion with [LinkML Map](https://linkml.io/linkml-map/). It's feature set has really been growing recently, but I have very little experience with it

So I have two suggestions for you:
1. Start thinking about the environment, workflow or tool-chain in which you will be applying your MIFC schema.  You're going to be interacting with databases at some point, right? (Not files) If so, then you should probably develop some familiarity with [LinkML-Store](https://linkml.io/linkml-store/) at some point.
2. It will be extremely valuable for you to participate in the [LinkML developer meeting](https://docs.google.com/document/d/1OOgBRPYVwcD0hbKc79EOKP750vVCLEKAtbztSMQdC7A/edit#heading=h.6sqkx1xhumse) every Friday or the monthly [LinkML community meetings](https://docs.google.com/document/d/1MStpDyh9LOZYJTjLtnpOsNYc3HaeU-bz0CHAI9xOjfQ/edit#heading=h.6sqkx1xhumse) on Thursdays, including next Thursday July 18th!

**Comment by kaiiam** [comment]
Thanks @turbomam I appreciate it. At the moment the plan is to use MIFC to validate and convert tabular data into JSON so that the USDA contractor Inonde can import it cleanly into a JSON or similar database of their choice/implementation. It could be good for them to check out [LinkML-Store](https://linkml.io/linkml-store/), I'll bring that to their attention. 

Yes I'm doing my best to make the LinkML meetings. 

@GregLyonJIFSAN based on Mark's answer there isn't an obvious linkML solution to this problem at the moment. So if we go with iso3 and PTFI is using Iso2 we'll need to use an external application (Python or R etc) to do that mapping.

**Comment by kaiiam** [comment]
Added.
